name: ParticlePlugin
version: '${project.version}'
main: io.github.thestorm135.particleplugin.ParticlePlugin
api-version: 1.18
authors: [ CyberWolfie ]
description: learning spigot particles
commands:
  Particle:
    description: summons a particl
    usage: /<command>
